alias: Heizungssteuerung-Komplett
description: Zentrale Heizungssteuerung für alle Räume, Pumpe und Dach
triggers:
  - trigger: time_pattern
    minutes: /3
  - trigger: state
    entity_id: switch.heizungdachboden
  - trigger: state
    entity_id: switch.fussbodenheizung
  - trigger: time
    at: "03:00:00"
  - trigger: time
    at: "05:30:00"
conditions: []
actions:
  - choose:
      - conditions:
          - condition: numeric_state
            entity_id: sensor.tempkue_temperatur
            below: 22.5
          - condition: state
            entity_id: switch.shellypro4pm_kuche
            state: "off"
        sequence:
          - action: switch.turn_on
            target:
              device_id: 13cb54d8fc840bb44b799146d71d29ad
      - conditions:
          - condition: numeric_state
            entity_id: sensor.tempkue_temperatur
            above: 22.5
          - condition: state
            entity_id: switch.shellypro4pm_kuche
            state: "on"
        sequence:
          - action: switch.turn_off
            target:
              device_id: 13cb54d8fc840bb44b799146d71d29ad
  - choose:
      - conditions:
          - condition: numeric_state
            entity_id: sensor.shellyhtg3_e4b32331f7cc_temperatur
            below: 22.5
          - condition: state
            entity_id: switch.shellypro4pm_so_zimmer
            state: "off"
        sequence:
          - action: switch.turn_on
            target:
              device_id: 8a404f2e4ed16b3279147dbcd9dd2619
      - conditions:
          - condition: numeric_state
            entity_id: sensor.shellyhtg3_e4b32331f7cc_temperatur
            above: 22.5
          - condition: state
            entity_id: switch.shellypro4pm_so_zimmer
            state: "on"
        sequence:
          - action: switch.turn_off
            target:
              device_id: 8a404f2e4ed16b3279147dbcd9dd2619
  - choose:
      - conditions:
          - condition: numeric_state
            entity_id: sensor.tempno_temperatur
            below: 22.5
          - condition: state
            entity_id: switch.shellypro4pm_no_zimmer
            state: "off"
        sequence:
          - action: switch.turn_on
            target:
              device_id: f99cb4e51c14b515a551587cde30cfec
      - conditions:
          - condition: numeric_state
            entity_id: sensor.tempno_temperatur
            above: 22.5
          - condition: state
            entity_id: switch.shellypro4pm_no_zimmer
            state: "on"
        sequence:
          - action: switch.turn_off
            target:
              device_id: f99cb4e51c14b515a551587cde30cfec
  - choose:
      - conditions:
          - condition: numeric_state
            entity_id: sensor.shellyhtg3_e4b3232f8980_temperatur
            below: 22.4
          - condition: state
            entity_id: switch.shelly4og_maria
            state: "off"
        sequence:
          - action: switch.turn_on
            target:
              device_id: 173ab4e12d8a06a86f5f409f37332d46
      - conditions:
          - condition: numeric_state
            entity_id: sensor.shellyhtg3_e4b3232f8980_temperatur
            above: 22.4
          - condition: state
            entity_id: switch.shelly4og_maria
            state: "on"
        sequence:
          - action: switch.turn_off
            target:
              device_id: 173ab4e12d8a06a86f5f409f37332d46
  - choose:
      - conditions:
          - condition: numeric_state
            entity_id: sensor.tmpmama_temperatur
            below: 22.4
          - condition: state
            entity_id: switch.shelly4og_mama
            state: "off"
        sequence:
          - action: switch.turn_on
            target:
              device_id: 16d8778957ec426e7f2b2ffced2d1386
      - conditions:
          - condition: numeric_state
            entity_id: sensor.tmpmama_temperatur
            above: 22.4
          - condition: state
            entity_id: switch.shelly4og_mama
            state: "on"
        sequence:
          - action: switch.turn_off
            target:
              device_id: 16d8778957ec426e7f2b2ffced2d1386
  - choose:
      - conditions:
          - condition: numeric_state
            entity_id: sensor.tmpjojo_temperatur
            below: 22.4
          - condition: state
            entity_id: switch.shelly4og_johannes
            state: "off"
        sequence:
          - action: switch.turn_on
            target:
              device_id: b8b808bed830c1999b26f1a1c5045151
      - conditions:
          - condition: numeric_state
            entity_id: sensor.tmpjojo_temperatur
            above: 22.4
          - condition: state
            entity_id: switch.shelly4og_johannes
            state: "on"
        sequence:
          - action: switch.turn_off
            target:
              device_id: b8b808bed830c1999b26f1a1c5045151
  - choose:
      - conditions:
          - condition: or
            conditions:
              - condition: state
                entity_id: switch.shellypro4pm_kuche
                state: "on"
              - condition: state
                entity_id: switch.shellypro4pm_so_zimmer
                state: "on"
              - condition: state
                entity_id: switch.shellypro4pm_no_zimmer
                state: "on"
              - condition: state
                entity_id: switch.shelly4og_maria
                state: "on"
              - condition: state
                entity_id: switch.shelly4og_mama
                state: "on"
              - condition: state
                entity_id: switch.shelly4og_johannes
                state: "on"
              - condition: state
                entity_id: switch.heizungdachboden
                state: "off"
              - condition: time
                after: "03:00:00"
                before: "05:30:00"
          - condition: state
            entity_id: switch.fussbodenheizung
            state: "off"
        sequence:
          - action: switch.turn_on
            target:
              entity_id: switch.fussbodenheizung
      - conditions:
          - condition: and
            conditions:
              - condition: state
                entity_id: switch.shellypro4pm_kuche
                state: "off"
              - condition: state
                entity_id: switch.shellypro4pm_so_zimmer
                state: "off"
              - condition: state
                entity_id: switch.shellypro4pm_no_zimmer
                state: "off"
              - condition: state
                entity_id: switch.shelly4og_maria
                state: "off"
              - condition: state
                entity_id: switch.shelly4og_mama
                state: "off"
              - condition: state
                entity_id: switch.shelly4og_johannes
                state: "off"
              - condition: state
                entity_id: switch.heizungdachboden
                state: "on"
          - condition: state
            entity_id: switch.fussbodenheizung
            state: "on"
          - condition: not
            conditions:
              - condition: time
                after: "03:00:00"
                before: "05:30:00"
        sequence:
          - action: switch.turn_off
            target:
              entity_id: switch.fussbodenheizung
mode: single
